### ISSUE TITLE
TK08 - Crear tabla de Favoritos en la Base de Datos

### ISSUE THREAD

**Issue by Yanina-Unrein** [Nervios-de-Acero/tesis-avocado#11]
Crear la tabla de favoritos en la base de datos para permitir a los usuarios agregar y quitar recetas de su lista de favoritos.

------------------------------------------------------------------------------------------------------------------------------------------------------
**Caso de Uso**: Agregar y Quitar Receta a Favoritos
**Dado** Un usuario desea agregar o quitar una receta a su lista de favoritos.
**Cuando** El usuario ejecuta la acción de agregar o quitar la receta a favoritos desde la interfaz de usuario.
**Entonces** La receta seleccionada se registra o se elimina en la tabla "favoritos" de la base de datos asociada al usuario correspondiente.

**Comment by Loreaylen** [comment]
No se implementarán favoritos por el momento.
