### ISSUE TITLE
TK02 - Crear los triggers de favoritos

### ISSUE THREAD

**Issue by FlorenciaItati** [Nervios-de-Acero/tesis-avocado#2]
**Descripción:**
Crear los triggers necesarios en la base de datos para implementar las funcionalidades de agregar y quitar las recetas favoritas de la sección de favoritos.

**Criterios de Aceptación:**

Caso de Uso: Agregar una receta Favorita
Dado que un usuario desea agregar o quitar una receta a su lista de favoritos.
Cuando el usuario envíe una solicitud a la base de datos para agregar o quitar un elemento como favorito.
Entonces el servidor deberá ejecutar un trigger que registre o elimine el elemento como favorito en la base de datos del usuario.

Relacionado a:
_____________

Bloqueado por:
_____________

**Comment by Loreaylen** [comment]
No se incorporarán favoritos por el momento.
