### ISSUE TITLE
HU3 - Normalización y Estandarización de la Base de Datos.

### ISSUE THREAD

**Issue by HernanRT** [Nervios-de-Acero/tesis-avocado#24]
Descripción:
Como administrador del proyecto Avocado
Quiero normalizar y estandarizar la base de datos.
Para mejorar la eficiencia, consistencia y mantenibilidad del sistema.

Criterios de Aceptación:
* Realizar un análisis exhaustivo de la base de datos existente para identificar posibles redundancias e inconsistencias.
* Normalizar la base de datos utilizando técnicas como la eliminación de duplicados, la división de tablas para evitar la repetición de datos y el establecimiento de relaciones adecuadas entre las tablas.
* Estandarizar la estructura de la base de datos siguiendo las mejores prácticas de diseño de bases de datos, incluyendo la nomenclatura consistente de tablas, columnas, claves primarias y foráneas.
* Documentar los cambios realizados en la estructura de la base de datos, incluyendo la descripción de las tablas, relaciones entre tablas y cualquier otra información relevante.
* Realizar pruebas exhaustivas para asegurar que los cambios de normalización y estandarización no afecten negativamente la funcionalidad existente del sistema.

Relacionado a:
Bloqueado por:

**Comment by Loreaylen** [comment]
Se reabre para introducir cambios en la base de datos.
