### ISSUE TITLE
TK22 - Unificar lógica de actualización de receta en un único SP

### ISSUE THREAD

**Issue by Uriel-98** [Nervios-de-Acero/tesis-avocado#33]
Tarea: Eliminar los stored procedures "actualizarCategoria", "actualizarIngredientes" y "actualizarPasos", y unificar su lógica dentro del stored procedure "actualizarDatosReceta".

Criterios de Aceptación:

Revisar los stored procedures existentes ("actualizarCategoria", "actualizarIngredientes" y "actualizarPasos").
Mover la lógica de actualización de categorías, ingredientes y pasos dentro del stored procedure "actualizarDatosReceta".
Cambiar el nombre del stored procedure "actualizarDatosReceta" a "sp_crearPasoIngredienteCategoria".
Asegurarse de que el stored procedure "actualizarReceta" pueda manejar la actualización de todos los datos de una receta de forma unificada.
Verificar que el código unificado sea coherente y fácil de mantener.
Caso de Uso: Unificación de Stored Procedures de Actualización de Receta

Dado que: se desea simplificar y unificar el código de los stored procedures relacionados con la actualización de categorías, ingredientes y pasos de una receta.
Cuando: se eliminen los stored procedures "actualizarCategoria", "actualizarIngredientes" y "actualizarPasos", y se unifique su lógica dentro del stored procedure "sp_crearPasoIngredienteCategoria".
Entonces: se tendrá un único procedimiento almacenado que maneje la actualización de todos los datos de una receta de forma unificada.

**Comment by Loreaylen** [comment]
El store procedure utilizado tiene como nombre sp_actualizarReceta.
