### ISSUE TITLE
TK06 - Crear procedimientos almacenados para favoritos (Get y Set)

### ISSUE THREAD

**Issue by tayVillarreal** [Nervios-de-Acero/tesis-avocado#8]
Crear los procedimientos almacenados en la base de datos para gestionar la funcionalidad de favoritos, incluyendo las operaciones de obtener (Get) y establecer (Set) favoritos para las recetas.

Criterios de aceptación:

Caso de uso: Gestión de favoritos
Dado que los usuarios desean marcar recetas como favoritas y acceder a ellas fácilmente,
Cuando se ejecuten los procedimientos almacenados correspondientes
Entonces las recetas podrán ser marcadas y desmarcadas como favoritas según la interacción del usuario.

Es bloqueado por:
TK-01 - Crear repositorio

**Comment by Loreaylen** [comment]
Por el momento no se implementarán los favoritos para los usuarios.
