### ISSUE TITLE
TK07 - Creación de Milestones del proyecto

### ISSUE THREAD

**Issue by Yanina-Unrein** [Nervios-de-Acero/tesis-avocado#9]
Crear los milestones necesarios en el repositorio del proyecto para demarcar y organizar los sprints, permitiendo a los miembros del equipo tener constancia de los sprints en curso y sus fechas de cierre.

Criterios de Aceptación:
Caso de Uso: Milestone para demarcar los Sprints del proyecto.
Dado que los miembros del equipo necesitan tener constancia del sprint en que se encuentran y cuándo cierra el mismo para gestionar las issues.
Cuando se cree el milestone del proyecto.
Entonces deberá colocársele la fecha de cierre y una breve descripción de lo que se espera de ese sprint.

-----------------------------------------------------------------------------------------------------------------------------------------------------
Es bloqueado por:
- #6

**Comment by Loreaylen** [comment]
Reabrir en los siguientes sprints
